---
- hosts: all
  become: true

  tasks:
  - name: creati Docker image
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/Docker

  - name: creatin tag for Docker image
    command: docker tag simple-devops-image loanji/simple-devops-image

  - name: pushing Docker image
    command: docker push loanji/simple-devops-image

  - name: Removing Docker image
    command: docker rmi simple-devops-image:latest loanji/simple-devops-image
    ignore_errors: yes
    
    
    
  

